import 'dart:math';

// Supabase Integration:
// Product IDs will be auto-generated by Supabase (UUID or serial)
// This generator is for temporary in-memory storage
class ProductIdGenerator {
  static String generate({
    required String productName,
    required String merchantId,
  }) {
    final now = DateTime.now();
    
    // Extract merchant code (e.g., "MS-0001" -> "MS0001")
    final merchantCode = merchantId
        .replaceAll('-', '')
        .replaceAll(' ', '')
        .toUpperCase()
        .substring(0, merchantId.length >= 4 ? 4 : merchantId.length)
        .padRight(4, 'X');
    
    // Extract first 3 letters of product name (uppercase, only letters)
    String namePart = productName
        .toUpperCase()
        .replaceAll(RegExp(r'[^A-Z]'), '');
    
    if (namePart.isEmpty) {
      namePart = 'PRD';
    } else if (namePart.length < 3) {
      namePart = namePart.padRight(3, 'X');
    } else {
      namePart = namePart.substring(0, 3);
    }
    
    // Date format: YYMMDD
    final datePart = '${now.year.toString().substring(2)}'
        '${now.month.toString().padLeft(2, '0')}'
        '${now.day.toString().padLeft(2, '0')}';
    
    // Time format: HHmmss
    final timePart = '${now.hour.toString().padLeft(2, '0')}'
        '${now.minute.toString().padLeft(2, '0')}'
        '${now.second.toString().padLeft(2, '0')}';
    
    // Random 3-digit number
    final random = Random().nextInt(900) + 100; // 100-999
    
    // Format: MERCHANT-NAME-DATE-TIME-RAND
    // Example: MS00-PAK-260708-121730-456
    return '$merchantCode-$namePart-$datePart-$timePart-$random';
  }
}
